
#-----------------------------------------------------------------------

APP       := ProtoBufDemo
TARGET    := MyProtoBufClient
CONFIG    := 
STRIP_FLAG:= N

INCLUDE   += -I..
LIB       += -lprotobuf

LOCAL_SRC += ../flight.pb.cc

#-----------------------------------------------------------------------

include /usr/local/tars/cpp/makefile/makefile.tars

#-----------------------------------------------------------------------
